### ISSUE TITLE
Todo list for this semester

### ISSUE THREAD

**Issue by pranavtbhat** [pranavtbhat/Networks.jl#3]
These are the things we need to finish off before the major project submission:
- [ ] Upload graphs in .dot, .json(sigma.js), .gexf etc
- [ ] Show basic structural information on the right hand side.
- [ ] Allow modifications of graphs.
